import React from "react";

import { Inter } from "next/font/google";

import "@/styles/reset.css";
import "@/styles/globals.css";

import Footer from "@/components/footer";
import Header from "@/components/header";

export const metadata = {
  title: "Nextfilms",
  description: "Generated by create next app and Made by Anıl Tülebağ",
};

const interFontFamily = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <html lang="en" className={interFontFamily.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
